# -*- coding: utf-8 -*-
"""ApexClustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nwKA05GbsHe4D8RwGI9f22oK7vUsKK3b

# Data Cleaning
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install bertopic sentence-transformers

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer

df = pd.read_csv("/content/drive/MyDrive/Apex_Legends_Steam_Reviews.csv")
df.head()

#Cleaning Data
#remove special characters from reviews
df["review"] = df["review"].str.replace(r'[^a-zA-Z0-9\s]', '', regex=True)

# Fill NaN values with empty strings before applying sentiment analysis
if df["review"].isnull().any():
    df.fillna({"review":""}, inplace=True)

from datetime import datetime

df["created"] = pd.to_datetime(df["created"]).dt.normalize()
df.tail()

#Split Data Into Seasons
seasons = {
    "Preseason": (datetime(2019, 2, 4),   datetime(2019, 3, 19)),
    "Season 1": (datetime(2019, 3, 19), datetime(2019, 6, 18)),
    "Season 2": (datetime(2019, 7, 2), datetime(2019, 10, 1)),
    "Season 3": (datetime(2019, 10, 1), datetime(2020, 2, 4)),
    "Season 4": (datetime(2020, 2, 4), datetime(2020, 5, 12)),
    "Season 5": (datetime(2020, 5, 12), datetime(2020, 8, 18)),
    "Season 6": (datetime(2020, 8, 18), datetime(2020, 11, 4)),
    "Season 7": (datetime(2020, 11, 4), datetime(2021, 2, 2)),
    "Season 8": (datetime(2021, 2, 2), datetime(2021, 5, 4)),
    "Season 9": (datetime(2021, 5, 4), datetime(2021, 8, 3)),
    "Season 10": (datetime(2021, 8, 3), datetime(2021, 11, 2)),
    "Season 11": (datetime(2021, 11, 2), datetime(2022, 2, 8)),
    "Season 12": (datetime(2022, 2, 8), datetime(2022, 5, 10)),
    "Season 13": (datetime(2022, 5, 10), datetime(2022, 8, 9)),
    "Season 14": (datetime(2022, 8, 9), datetime(2022, 11, 1)),
    "Season 15": (datetime(2022, 11, 1), datetime(2023, 2, 14)),
    "Season 16": (datetime(2023, 2, 14), datetime(2023, 5, 9)),
    "Season 17": (datetime(2023, 5, 9), datetime(2023, 8, 8)),
    "Season 18": (datetime(2023, 8, 8), datetime(2023, 10, 31)),
    "Season 19": (datetime(2023, 10, 31), datetime(2024, 2, 13)),
    "Season 20": (datetime(2024, 2, 13), datetime(2024, 5, 6)),
    "Season 21": (datetime(2024, 5, 7), datetime(2024, 8, 6)),
    "Season 22": (datetime(2024, 8, 6), datetime(2024, 11, 5)),
    "Season 23": (datetime(2024, 11, 5), datetime(2025, 2, 11)),
    "Season 24": (datetime(2025, 2, 11), datetime(2025, 5, 6)),
    "Season 25": (datetime(2025, 5, 6), datetime(2025, 7, 5)),
}

#Data Starts at Season 15
start, end = seasons["Season 15"]
s15_mask = (df['created'] >= start) & (df['created'] <= end)
df_s15 = df.loc[s15_mask]
df_s15["voted_up"].value_counts().plot(kind= "bar",
          title = "Votes Up or Down",
          figsize = (10,5))

start, end = seasons["Season 16"]
s16_mask = (df['created'] >= start) & (df['created'] <= end)
df_s16 = df.loc[s16_mask]
df_s16.tail()
df_s16["voted_up"].value_counts().plot(kind= "bar",
          title = "Votes Up or Down",
          figsize = (10,5))

start, end = seasons["Season 17"]
s17_mask = (df['created'] >= start) & (df['created'] <= end)
df_s17 = df.loc[s17_mask]
df_s17.tail()
df_s17["voted_up"].value_counts().plot(kind= "bar",
          title = "Votes Up or Down",
          figsize = (10,5))

start, end = seasons["Season 18"]
s18_mask = (df['created'] >= start) & (df['created'] <= end)
df_s18 = df.loc[s18_mask]
df_s18.tail()
df_s18["voted_up"].value_counts().plot(kind= "bar",
          title = "Votes Up or Down",
          figsize = (10,5))

start, end = seasons["Season 19"]
s19_mask = (df['created'] >= start) & (df['created'] <= end)
df_s19 = df.loc[s19_mask]
df_s19.head()
#Data Ends at Season 19
df_s19["voted_up"].value_counts().plot(kind= "bar",
          title = "Votes Up or Down",
          figsize = (10,5))

"""# Clustering

"""

df_s15.head()

embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

topic_model = BERTopic(
    embedding_model=embedding_model,
    verbose=True,
    min_topic_size=50   # merge small clusters
)

reviews = df["review"].tolist()

topics, probs = topic_model.fit_transform(reviews)

# Store topic assignments
df["topic"] = topics

"""# Sentiment Analysis"""

from transformers import pipeline

sentiment_model = pipeline(
    "sentiment-analysis",
    model="cardiffnlp/twitter-roberta-base-sentiment"
)

#Get Sentiments for Batches

sentiments = []
batch_size = 32
for start in range(0, len(reviews), batch_size):
    chunk = reviews[start:start+batch_size]
    results = sentiment_model(chunk, truncation=True, max_length=512)
    sentiments.extend([r["label"] for r in results])

df["sentiment"] = sentiments

#Sentiment Summary per Topic

timestamps = df["created"].tolist()

sent_summary = (
    df.groupby("topic")["sentiment"]
    .value_counts(normalize=True)
    .unstack(fill_value=0)
    .sort_index()
)

topics_over_time = topic_model.topics_over_time(
    reviews, timestamps, nr_bins=20
)

topic_model.visualize_topics_over_time(topics_over_time)

import os

# Create a folder for visualizations
os.makedirs("visualizations", exist_ok=True)

# Save topic overview (scatterplot of topics)
fig_overview = topic_model.visualize_topics()
fig_overview.write_html("visualizations/topic_overview.html")

# Save topics over time
fig_trends = topic_model.visualize_topics_over_time(topics_over_time)
fig_trends.write_html("visualizations/topic_trends.html")

from google.colab import files
files.download("visualizations/topic_overview.html")
files.download("visualizations/topic_trends.html")